# Generated by Django 2.2 on 2020-03-03 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 3, 6, 52, 11, 282531, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
