# Generated by Django 2.2 on 2020-07-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200718_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_date',
        ),
    ]
