# Generated by Django 2.2 on 2020-07-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_file_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_date',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
